server:
    port: 9888

application:
    unidbg:
        dynarmic: true
        verbose: false
        async: true
        soPrefix: data/apks/so/
        apkPath: apks/puji.apk
spring:
    task:
        execution:
            pool:
                allow-core-thread-timeout: true
                core-size: 8
                keep-alive: 60s
                max-size: 8
