server:
    port: 9999

application:
    unidbg:
        dynarmic: true
        verbose: false
        async: true
        soPrefix: data/apks/so/


spring:
    application:
        name: unidbg-boot-server
    profiles:
        active: prod
